# Alacritty configuration
#
# Configuration for Alacritty with sensible defaults, the GPU enhanced terminal emulator.

# Setup term for programs to be able to use it
env:
  TERM: alacritty

# Font configuration
font:
  # Normal font settings
  normal:
    family: BerkeleyMono
    style: Medium
  # Bold font settings
  bold:
    family: BerkeleyMono
    style: Bold
  # Italic font settings
  italic:
    family: BerkeleyMono
    style: Italic
  # Bold Italic font settings
  bold_italic:
    family: BerkeleyMono
    style: BoldItalic
# Font size
font_size: 16.0

# Offset for character spacing is the extra space around each character. `offset.y`
# can be thought of as modifying the line spacing, and `offset.x` as modifying the
# letter spacing I've given in 14 spacing which fits really well with my fonts, you
# may change it to your convenience but make sure to adjust 'glyph_offset' appropriately post that
offset:
  x: 0
  y: 15

  # Better font rendering for mac
  use_thin_strokes: true

# Theme configuration
colors:
  # Default colors
  primary:
    background: '0x1e1e1e'
    foreground: '0xe0e0e0'

  # Normal colors
  normal:
    black: '0x000000'
    red: '0xff5370'
    green: '0xc3e88d'
    yellow: '0xffcb6b'
    blue: '0x82aaff'
    magenta: '0xc792ea'
    cyan: '0x89ddff'
    white: '0xeeeeee'

  # Bright colors
  bright:
    black: '0x666666'
    red: '0xff5370'
    green: '0xc3e88d'
    yellow: '0xffcb6b'
    blue: '0x82aaff'
    magenta: '0xc792ea'
    cyan: '0x89ddff'
    white: '0xffffff'

# Window settings
window:
  padding:
    x: 16
    y: 16
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1  # Adjust window opacity as needed (0 = fully transparent, 1 = fully opaque)

# Scrolling settings
scrolling:
  history: 10000  # Maximum lines of scrollback history
  multiplier: 3   # Number of lines to scroll with each scroll action

# Selection
selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Key bindings
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  # Scroll up one page
  - { key: PageUp,   mods: Control, action: ScrollPageUp }
  # Scroll down one page
  - { key: PageDown, mods: Control, action: ScrollPageDown }
  # Paste from clipboard
  - { key: V, mods: Control|Shift, action: Paste }
  # Copy to clipboard
  - { key: C, mods: Control|Shift, action: Copy }

# Allow applications to change window title
allow_change_title: true

# Live config reload (changes require restart)
live_config_reload: true

# Shell settings
shell:
  program: /bin/zsh
  args:
  # Start tmux if available
  - -l
  - -c
  - "tmux attach || tmux"
