tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Packages to install
brew "ack"
brew "antidote"
brew "bash"
brew "bash-completion"
brew "bash-snippets"
brew "bat"
brew "bpytop"
brew "broot"
brew "calcurse"
brew "chkrootkit"
brew "cointop"
brew "coreutils"
brew "ctop"
brew "ddgr"
brew "diff-so-fancy"
brew "exa"
brew "fd"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "glances"
brew "go"
brew "gzip"
brew "htop"
brew "httpie"
brew "ideviceinstaller ios-deploy cocoapods"
brew "jq"
brew "lazydocker"
brew "mackup"
brew "map"
brew "mas"
brew "moreutils"
brew "n"
brew "nano"
brew "neofetch"
brew "npm"
brew "osxutils"
brew "pup"
brew "pyenv"
brew "python3"
brew "ranger"
brew "rbenv"
brew "recode"
brew "ripgrep"
brew "rust"
brew "spoof-mac"
brew "starship"
brew "stow"
brew "terminal-notifier"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "vim"
brew "webp"
brew "weechat"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "z"
brew "zoxide"
brew "zsh"
brew "zsh-completions"

# Fonts
#cask "font-atkinson-hyperlegible"
#cask "font-blokk"
#cask "font-blokk-neue"
#cask "font-cascadia-code"
#cask "font-fira-code"
#cask "font-inconsolata-dz"
#cask "font-open-sans"
#cask "font-open-sans-condensed"
#cask "font-source-code-pro"

# Personal (uncomment as needed)
#cask "1password7"
#cask "adobe-creative-cloud"
#cask "adobe-digital-editions"
#cask "adobe-dng-converter"
#cask "android-file-transfer"
#cask "anki"
#cask "battle-net"
#cask "calibre"
#cask "cityofzion-neon"
#cask "discord"
#cask "dropbox"
#cask "exodus"
#cask "figma"
#cask "firefly"
#cask "folding-at-home"
#cask "google-backup-and-sync"
#cask "heroku update"
#cask "heroku-toolbelt"
#cask "imazing"
#cask "ledger-live"
#cask "little-snitch5"
#cask "nault" #Wallet for the Nano cryptocurrency with support for hardware wallets
#cask "notion" #App to write, plan, collaborate, and get organized
#cask "openemu" #Retro video game emulation
#cask "opera-beta"
#cask "overdrive-media-console" #Get eBooks, audiobooks, and videos from your local library
#cask "plex-media-server" #Home media server
#cask "protonvpn" #VPN client focusing on security
#cask "sia-ui"
#cask "signal-beta"
#cask "slack-beta"
#cask "steam"
#cask "suspicious-package"
#cask "telegram-desktop-beta"
#cask "tor-browser"
#cask "transmission-nightly"
#cask "tuxera-ntfs"
#cask "veracrypt"
#cask "vlc-nightly"
#cask microsoft-office
#cask microsoft-outlook
#cask "zoom"

# Work
cask "alfred"
cask "arduino-nightly"
cask "arq5"
cask "automute"
cask "balenaetcher"
cask "bartender"
cask "brave-browser-nightly"
cask "caffeine"
cask "cheatsheet"
cask "daisydisk"
cask "dash"
cask "dbeaver-community"
cask "docker"
cask "docker-toolbox"
cask "firefox-nightly"
cask "flutter"
cask "flux"
cask "github"
cask "google-chrome-canary"
cask "gpg-suite-nightly"
cask "gyazo"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "install-disk-creator"
cask "iterm2-nightly"
cask "licecap"
cask "local" #WordPress local development tool by Flywheel
cask "macfuse" #needed for veracrypt
cask "macvim"
cask "micro-snitch"
cask "raspberry-pi-imager"
cask "sequel-pro"
cask "shortcat"
cask "shottr"
cask "spectacle"
cask "spotify"
cask "sublime-text-dev"
cask "thonny"
cask "transmit"
cask "utm" #Virtual machines UI using QEMU
cask "visual-studio-code-insiders"
cask "xld"
cask "yubico-authenticator"

# quicklook plugins
cask "betterzipql"
cask "epsqlplugin"
cask "epub-quicklook"
cask "qlcolorcode"
cask "qlgradle"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlmobi"
cask "qlmoviepreview"
cask "qlplayground"
cask "qlstephen"
cask "qlswift"
cask "qltorrent"
cask "qlvideo"
cask "qlwoff"
cask "quickjson"
cask "quicklook-json"
cask "quicklookase"
cask "quicknfo"
cask "syntax-highlight"
cask "webpquicklook"
