# Set Variables
export NULLCMD=bat # Syntax highlighting for man pages using bat
export DOTFILES="$HOME/.dotfiles"
export HOMEBREW_BUNDLE_FILE="$DOTFILES/Brewfile"
export UPDATE_ZSH_DAYS=1

# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Change ZSH Options
ZSH_THEME="clean-minimal"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git z docker docker-compose)


source $ZSH/oh-my-zsh.sh

# Adjust History Variables & Options
[[ -z $HISTFILE ]] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000 # Session Memory Limit
SAVEHIST=4000 # File Memory Limit
setopt histNoStore
setopt extendedHistory
setopt histIgnoreAllDups
unsetopt appendHistory # explicit and unnecessary
setopt incAppendHistoryTime

# Line Editor Options (Completion, Menu, Directory, etc.)
# autoMenu & autoList are on by default
setopt autoCd
setopt globDots

# Create Aliases
alias ls='exa' # List files and directories with enhanced formatting
alias lsh='ls -lAd .*' # Show ONLY hidden files in the current directory
alias hid='ls -lAd .*' # Alias for lsh
alias exa='exa -laFh --git' # List files and directories with enhanced formatting (including Git status)
alias trail='<<<${(F)path}' # Show the contents of the $path array
alias ftrail='<<<${(F)fpath}' # Show the contents of the $fpath array
alias mkdir='mkdir -p' # Create directories (including parent directories if needed)
alias rm='trash' # Move files to the trash instead of deleting permanently
alias man='batman' # Use batman as the man page viewer
alias bbd='brew bundle dump --force --describe' # Dump the list of installed Homebrew packages to a Brewfile

# Load history into shell (shareHistory alternative)
alias lh='fc -RI; echo "loaded and showing..."; history;' # Load and display the command history

alias cd..='cd ..' # Shortcut for "cd .."
alias cd.....='cd ../../' # Shortcut for "cd ../../"
alias up='cd ../' # Shortcut for "cd ../"
alias c='clear' # Shortcut for "clear"
alias h='history' # Shortcut for "history"

alias zshreload='source ~/.zshrc' # Reload the .zshrc file
alias zshconfig='mate ~/.zshrc' # Open .zshrc file in TextMate editor
alias ohmyzsh='mate ~/.oh-my-zsh' # Open oh-my-zsh installation directory in TextMate editor

# Apache
alias ap2start='sudo service apache2 start' # Start Apache service
alias ap2restart='sudo service apache2 restart' # Restart Apache service
alias ap2stop='sudo service apache2 stop' # Stop Apache service

# Git Commands
alias g='git' # Shortcut for "git"
alias gst='git status' # Shortcut for "git status"

# Goto the root of the (git) directory.
alias groot='echo "I am Groot."; cd "$(git rev-parse --show-toplevel)"' # Go to the root directory of the Git repository

# Enable aliases to be sudo'ed
alias sudo='sudo' # Enable aliases to be used with sudo

alias cask='brew cask' # Shortcut for "brew cask"

# Recursively remove .DS_Store files
alias cleanupds='find . -type f -name "*.DS_Store" -ls -delete' # Remove all .DS_Store files recursively

# Source extra files
# source ~/.aliases
# source ~/.functions

# Add Locations to $path Array
typeset -U path

path=(
  "$N_PREFIX/bin"
  $path
  "/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"
)

# Use ZSH Plugins
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# Source antidote
source <(antidote init) # Initialize antidote shell extension
antidote bundle < "$DOTFILES/antidote_plugins" # Load bundled antidote plugins
antidote update # Update antidote plugins
antidote load # Load antidote plugins
